### ISSUE TITLE
No package description on pypi.org

### ISSUE THREAD

**Issue by natct10** [SubstraFoundation/substra-tools#25]
The description of the package [substratools](https://pypi.org/project/substratools/) is not fetched from the `setup.py` file whereas it is working for the [substra](https://pypi.org/project/substra/) package. On both projects, the uploader had a travis token added before. 
Any idea why this is happening? 
It would be great to have `description='Python tools to submit algo on the Substra platform'` displayed to the world!

**Comment by jmorel** [comment]
The description is included, in the grey banner under the dark blue one. The difference is that substra specifies a long_description as well.

**Comment by natct10** [comment]
Okay, thank you, my bad!

**Comment by jmorel** [comment]
Having a proper long description wouldn't be bad though!

**Comment by samlesu** [comment]
Fixed by https://github.com/SubstraFoundation/substra-tools/pull/28.
