### ISSUE TITLE
Algos: do not load list of models in memory

### ISSUE THREAD

**Issue by samlesu** [SubstraFoundation/substra-tools#32]
We could use a generator to load them when needed, it will be needed to avoid running out of memory.

To be updated:
- traintuple.models
- aggregatetuple.models

**Comment by jmorel** [comment]
In order not to break existing code with an update, we could add a flag to the Traintuple and AggregateTuple classes that would drive whether models are loaded using a generator or not. 

The flag could be `use_models_generator` and be at False by default.
