### ISSUE TITLE
Get rid of substratools docker images

### ISSUE THREAD

**Issue by samlesu** [SubstraFoundation/substra-tools#8]
As substratools is now open source we don't need to build and provide docker images.
End users could directly install subtratools through pip and don't need to create a Dockerfile inheriting from substratools.

It will allow them to choose the base image.

One of the issue is that currently substra-backend relies on the fact that the working directory inside the container is `/sandbox` (hardcoded value).

That's the reason why to get rid of the substratools, we must first ensure that:
- all paths can be defined in substratools command line interfaces
- substra-backend is passing the expected paths through the command line interface

We will then be able to update all the Dockerfile and stop inheriting from substratools images.

**EDIT:** 

⚠️ The substra-tools image is really useful for a quick development loop: update substratools code, rebuild the image and launch the tests locally. If substratools is installed from pypi in the end to end tests, we won't be able to test new substratools changes. So I think, we should continue to publish substratools docker images to the docker registry and use them for the end to end tests.

**Comment by Kelvin-M** [comment]
This issue could be closed. As @samlesu said, the image is usefull for development loop, but also as a base image for people that want to start from an existing image.

**Comment by samlesu** [comment]
I think it will still be useful to be able to create a Docker image without depending on a substratools base image. It will allow to change the python version or the base docker image (cuda or something else).

If we don't allow it we may have to maintain and build a list of docker images.

**Comment by Kelvin-M** [comment]
Yes, but one doesn't exclude the other. The Dockerfile to build the substratools docker image can be use as an example to create its own docker image. We can add a part on this in the documentation for it.

**Comment by samlesu** [comment]
You're right. 
I will close this ticket and create a new one if that's ok with you (goal: allow creation of Dockerfile without substratools base image).
